### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by EmpellorCRM** [opc-cpvp/OPC.PowerApps.PCFControls#19]
The configuration document is confusing on how this should be setup.  I setup an entity to contain the tags (new_marketingtags).  I setup another entity (new_contactmarketingtags) to act as the N:N container for linking the tag entity to the contact entity.  This entity has a N:1 from Contact and a N:1 from new_marketingtags.  I setup it this way because the documentation is not clear if I should have used the out-of-the-box N:N relationship between Contact and Marketing Tags and I assumed from experience that you instead intended the use of a custom entity to store the N:N relationship.

I configured the control as follows:

Tag Data: name of the attribute on Contact that allows the user to select the tags on the form.
Related Entity: name of the tag entity (new_marketingtags)
Relationship Name: name of the relationship from Contact to the N:N custom entity
Relationship Entity: name of the custom N:N entity

![image](https://user-images.githubusercontent.com/53800179/91497881-fce97080-e87b-11ea-8d68-1f7ada0f7561.png)

When I view the contact form, I can display and select tags without issue, but it is not storing the tags in the custom N:N entity.

Can you please elaborate on the configuration as we are very excited to implement this control.

**Comment by joshcampbell191** [comment]
Hello @EmpellorCRM,

It sounds like you're close with the configuration as you seem to have the tags loading. Please note that our control relies on the out-of-the-box N:N relationship in order to store the relations. As a such, the "Relationship Entity" property should be set to the "Relationship entity name" property of the N:N relationship.

In the example below, we created an N:N relationship between the Complaint and Topics (a complaint can have many topics / a topic can belong to many complaints) entity. The "Relationship Entity" property of the tag picker control is set to the "Relationship entity name" of the property (opc_complaintsrelatedtopics) of the relationship.

![Relationship Entity](https://user-images.githubusercontent.com/1784236/91560014-1aafe780-e907-11ea-97b3-7fda5d041dd8.png)

Hope this clears things up.

Regards,
Joshua Campbell

**Comment by joshcampbell191** [comment]
@EmpellorCRM I will be marking this issue as closed. If you feel like your question was unanswered, please re-open the issue. Thanks!
